version: "3"
services:
 hub:
   image: selenium/hub:3.141.59
 chrome:
   image: selenium/node-chrome:3.141.59
   shm_size: '1gb'
   depends_on:
     - hub
   environment:
     - HUB_HOST=hub
 firefox:
   image: selenium/node-firefox:3.141.59
   shm_size: '254mb'
   depends_on:
     - hub
   environment:
     - HUB_HOST=hub
 test-module-one:
    image: lautarorial/selenium-docker
    depends_on: 
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=module_one.xml
    volumes:
      - ./output/module-one-test-results:/tests/test-output
 test-module-two:
    image: lautarorial/selenium-docker
    depends_on: 
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=module_two.xml
    volumes:
      - ./output/module-two-test-results:/tests/test-output